# Generated by Django 5.1.1 on 2024-11-22 06:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('bus_id', models.AutoField(primary_key=True, serialize=False)),
                ('plate_number', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('make', models.CharField(max_length=100)),
                ('year', models.DateField()),
                ('capacity', models.IntegerField()),
                ('status', models.CharField(choices=[('on_standby', 'On Standby'), ('in_transit', 'In Transit'), ('under_maintenance', 'Under Maintenance')], max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
