# Generated by Django 5.1.1 on 2024-11-23 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bms_bus_information_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bus',
            name='plate_number',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
