# Generated by Django 5.1.1 on 2024-11-23 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bms_bus_information_management', '0002_alter_bus_plate_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bus',
            name='status',
            field=models.CharField(choices=[('on_standby', 'On Standby'), ('in_transit', 'In Transit'), ('under_maintenance', 'Under Maintenance')], default='on_standby', max_length=50),
        ),
    ]
