# Generated by Django 5.1.1 on 2024-11-23 16:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bms_bus_information_management', '0003_alter_bus_status'),
        ('bms_bus_schedule_management', '0001_initial'),
        ('bms_driversworkers_management', '0002_alter_employee_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='departure_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='status',
            field=models.CharField(choices=[('on_standby', 'On Standby'), ('in_transit', 'In Transit'), ('arrived', 'Arrived')], default='on_standby', max_length=50),
        ),
        migrations.CreateModel(
            name='ScheduleHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route', models.CharField(max_length=100)),
                ('departure_time', models.DateTimeField(blank=True, null=True)),
                ('arrival_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(max_length=50)),
                ('frequency', models.CharField(blank=True, max_length=50, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bms_bus_information_management.bus')),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bms_driversworkers_management.employee')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='bms_bus_schedule_management.schedule')),
            ],
        ),
    ]
