# Generated by Django 5.1.1 on 2024-11-23 16:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bms_bus_schedule_management', '0002_alter_schedule_departure_time_alter_schedule_status_and_more'),
        ('bms_driversworkers_management', '0002_alter_employee_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='bms_driversworkers_management.employee'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='frequency',
            field=models.CharField(blank=True, default=1, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='schedulehistory',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bms_driversworkers_management.employee'),
        ),
    ]
