# Generated by Django 5.1.2 on 2024-12-04 01:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bms_bus_information_management', '0003_alter_bus_status'),
        ('bms_bus_schedule_management', '0005_alter_schedule_employee'),
        ('bms_driversworkers_management', '0002_alter_employee_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='bus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bms_bus_information_management.bus', unique=True),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='bms_driversworkers_management.employee', unique=True),
        ),
    ]
