# Generated by Django 5.1.2 on 2024-12-04 11:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bms_bus_information_management', '0003_alter_bus_status'),
        ('bms_bus_schedule_management', '0008_alter_schedule_bus_alter_schedule_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='bus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bms_bus_information_management.bus'),
        ),
    ]
