# Generated by Django 5.1.1 on 2024-10-13 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bms_app', '0002_bus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bus',
            name='license_number',
        ),
    ]
