# Generated by Django 5.1.1 on 2024-10-13 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bms_app', '0005_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bus',
            name='status',
            field=models.CharField(choices=[('on_standby', 'On Standby'), ('in_transit', 'In Transit'), ('under_maintenance', 'Under Maintenance')], max_length=50),
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
