# Generated by Django 5.1.1 on 2024-10-13 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bms_app', '0008_schedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='arrival_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
