# Generated by Django 5.1.1 on 2024-10-13 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bms_app', '0009_alter_schedule_arrival_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='employee_type',
            field=models.CharField(choices=[('driver', 'Driver'), ('mechanic', 'Mechanic')], max_length=50),
        ),
    ]
