# Generated by Django 5.1.1 on 2024-10-13 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bms_app', '0010_alter_employee_employee_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='frequency',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='schedule',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='schedule',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
