# Generated by Django 5.1.1 on 2024-10-13 19:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bms_app', '0011_schedule_frequency_schedule_last_updated_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='employee_type',
        ),
        migrations.AddField(
            model_name='employee',
            name='contact_no',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='date_of_hire',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='employee',
            name='job_title',
            field=models.CharField(blank=True, choices=[('driver', 'Driver'), ('mechanic', 'Mechanic')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='middle_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='status',
            field=models.CharField(blank=True, choices=[('active', 'Active'), ('inactive', 'Inactive')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
