# Generated by Django 5.1.2 on 2024-11-03 10:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bms_app', '0014_alter_repair_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='bms_app.employee'),
        ),
    ]
