# Generated by Django 5.1.1 on 2024-11-04 06:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bms_app', '0015_schedule_employee'),
    ]

    operations = [
        migrations.CreateModel(
            name='DriverSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('days_active', models.CharField(help_text="E.g., 'Mon-Fri' or 'Mon,Wed,Fri'", max_length=50)),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bms_app.bus')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bms_app.employee')),
            ],
        ),
    ]
