# Generated by Django 5.1.1 on 2024-11-22 17:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bms_bus_information_management', '0001_initial'),
        ('bms_driversworkers_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Repair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repair_desc', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('est_completion', models.DateField()),
                ('status', models.CharField(choices=[('under_maintenance', 'Under Maintenance'), ('done', 'Done')], max_length=100)),
                ('repair_cost', models.FloatField()),
                ('parts_used', models.CharField(max_length=255)),
                ('follow_action', models.CharField(max_length=255)),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bms_bus_information_management.bus')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bms_driversworkers_management.employee')),
            ],
        ),
    ]
