# Generated by Django 5.1.1 on 2024-11-22 12:41

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bms_bus_information_management', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('employee_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
                ('contact_no', models.CharField(blank=True, max_length=30, null=True)),
                ('status', models.CharField(blank=True, choices=[('active', 'Active'), ('inactive', 'Inactive')], max_length=100, null=True)),
                ('job_title', models.CharField(blank=True, choices=[('driver', 'Driver'), ('mechanic', 'Mechanic')], max_length=100, null=True)),
                ('date_of_hire', models.DateField(default=django.utils.timezone.now)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='employee_photos/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DriverSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('days_active', models.CharField(help_text="E.g., 'Mon-Fri' or 'Mon,Wed,Fri'", max_length=50)),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bms_bus_information_management.bus')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bms_driversworkers_management.employee')),
            ],
        ),
    ]
